### ISSUE TITLE
 module 'fastimage' not found

### ISSUE THREAD

**Issue by Timo-hab** [e-lab/ENet-training#21]
I want to test ENet. I enter the following in the terminal:

```
qlua demo.lua -i /home/timo/example_image/004.png -m /home/timo/ENet-training/model/model-best.net
```

Then I get the following output:

```
Found Environment variable CUDNN_PATH = /usr/local/cuda/lib64/libcudnn.so.5
GPU # 1 selected
Loading model from: /home/timo/ENet-training/model/model-best.net
No stat file found in directory: /home/timo/ENet-training/model/home/timo/ENet-training/model/model-best.net
newcatdir= /home/timo/ENet-training/model/categories.txt
Loading categories file from: /home/timo/ENet-training/model/categories.txt
/home/timo/ENet-training/model/categories.txt
Network has this list of categories, targets:
1   Unlabeled   true
2   Road    true
3   Sidewalk    true
4   Building    true
5   Wall    true
6   Fence   true
7   Pole    true
8   TrafficLight    true
9   TrafficSign true
10  Vegetation  true
11  Terrain true
12  Sky true
13  Person  true
14  Rider   true
15  Car true
16  Truck   true
17  Bus true
18  Train   true
19  Motorcycle  true
20  Bicycle true
qlua: ./frame/frameimage.lua:17: module 'fastimage' not found:
    no field package.preload['fastimage']
    no file '/home/timo/.luarocks/share/lua/5.1/fastimage.lua'
    no file '/home/timo/.luarocks/share/lua/5.1/fastimage/init.lua'
    no file '/home/timo/torch/install/share/lua/5.1/fastimage.lua'
    no file '/home/timo/torch/install/share/lua/5.1/fastimage/init.lua'
    no file './fastimage.lua'
    no file '/home/timo/torch/install/share/luajit-2.1.0-beta1/fastimage.lua'
    no file '/usr/local/share/lua/5.1/fastimage.lua'
    no file '/usr/local/share/lua/5.1/fastimage/init.lua'
    no file '/home/timo/torch/install/lib/fastimage.so'
    no file '/home/timo/.luarocks/lib/lua/5.1/fastimage.so'
    no file '/home/timo/torch/install/lib/lua/5.1/fastimage.so'
    no file './fastimage.so'
    no file '/usr/local/lib/lua/5.1/fastimage.so'
    no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
    [C]: at 0x7f5bf93969c0
    [C]: in function 'require'
    ./frame/frameimage.lua:17: in function 'init'
    demo.lua:147: in main chunk
```

"luarocks install fastimage" does not work unfortunately. Does somebody has an idea? Thank you in advance!

**Comment by Timo-hab** [comment]
I had to put "fastimage.so" to one of the specified paths. Now it works.

**Comment by deepcode123** [comment]
hi, @Timo-hab 
I have the same problem as you, so how do you fix this it?
Where do you find "fastimage.so" ?
Thank you!

**Comment by Timo-hab** [comment]
@deepcode123 
I think i founded it somewhere on my system. Just searched for it.

**Comment by deepcode123** [comment]
@Timo-hab 
I found it!!! Thank you for your sharing

**Comment by codeAC29** [comment]
Follow the instructions provided [here](https://github.com/e-lab/torch-toolbox/tree/master/Video-decoder) for `fastimage`.

**Comment by deepcode123** [comment]
@codeAC29 
Thank you so much, it can work!

**Comment by MikepX99** [comment]
Sorry to revisit this old topic but where exactly do you put the fastimage.so  file?  I cloned the torch toolbox from https://github.com/e-lab/torch-toolbox and used make on the Video-decoder but I still get the same error.  Do I have to move the fastimage.so file to my torch/instal/lib to get it to work?
