### ISSUE TITLE
Running semantic segmentation with a different model file, on a different dataset.

### ISSUE THREAD

**Issue by ishann** [e-lab/ENet-training#29]
I found the code quite readable and newbie-friendly, and am trying to build my own semantic segmentation repository based off of ENet. For now, the details have been abstracted away to get the system up and running.

I'm working with my own dataset - img: 256x256, lab: 128x128 (architecture has 1 2x2 pooling). A loadDataset.lua script generates the data/labels as 4D tensors : numFiles X channels X hgt X wdt. A Resnet-style model is called from run.lua for training an epoch [trying to figure out only training for now] as follows:
```
epoch = 1
trainConf, model, loss = trainer(data.trainData, opt.dataClasses, epoch);
```

I am getting the following error:
```
==> Training: epoch # 1 [batchSize = 128]
THCudaCheck FAIL file=/home/ishann/torch/extra/cutorch/lib/THC/generic/THCStorage.cu line=41 error=2 : out of memory
/home/ishann/torch/install/share/lua/5.1/nn/Container.lua:67:
In 5 module of nn.Sequential:
In 1 module of nn.Sequential:
In 3 module of nn.Sequential:
In 1 module of nn.ConcatTable:
In 1 module of nn.Sequential:
...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:142: cuda runtime error (2) : out of memory at /home/ishann/torch/extra/cutorch/lib/THC/generic/THCStorage.cu:41
stack traceback:
        [C]: in function 'resize'
        ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:142: in function 'createIODescriptors'
        ...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:349: in function <...torch/install/share/lua/5.1/cudnn/SpatialConvolution.lua:347>
        [C]: in function 'xpcall'
        /home/ishann/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/ishann/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function </home/ishann/torch/install/share/lua/5.1/nn/Sequential.lua:41>
        [C]: in function 'xpcall'
        /home/ishann/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        ...e/ishann/torch/install/share/lua/5.1/nn/ConcatTable.lua:11: in function <...e/ishann/torch/install/share/lua/5.1/nn/ConcatTable.lua:9>
        [C]: in function 'xpcall'
        ...
        /home/ishann/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
        /home/ishann/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
        ./trainer.lua:78: in function 'opfunc'
        /home/ishann/torch/install/share/lua/5.1/optim/sgd.lua:44: in function 'sgd'
        ./trainer.lua:94: in function 'trainer'
        [string "trainConf, model, loss = trainer(data.trainDa..."]:1: in main chunk
        [C]: in function 'xpcall'
        /home/ishann/torch/install/share/lua/5.1/trepl/init.lua:669: in function 'repl'
        ...ushb/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
        [C]: at 0x00406670
```

I am currently working with a single GPU and have removed the dataParallelTable code segment from my model file. The model and loss have been converted to CUDA formats.

Environment : Ubuntu-14.04, TitanX GPU, CUDA V7.0.27, Driver Version 346.35.

**Comment by Mina1368** [comment]
Hi,

I am not sure, but it seems your CUDA has problem, try to run one sample of CUDA.

could you use cudnn, cunn, or cutorch?

**Comment by codeAC29** [comment]
Since you are using batch size of 128, you are running out of memory. Try to reduce it 8 or even less than that.

**Comment by ishann** [comment]
@Mina1368 I have run fb.resnet.torch using cudnn, cunn. That does not appear to be the problem.

@codeAC29 Yes, that fixed it. I did not realize segmentation (compared to classification) is so resource intensive. Thank you!
